---
apiVersion: v1
kind: Service
metadata:
  name: hackazon
spec:
  type: NodePort
  selector:
    app: hackazon
  ports:
  - name: dvwa
    port: 80
    targetPort: 80
    nodePort: 30009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackazon-deployment
spec:
  selector:
    matchLabels:
      app: hackazon
  replicas: 1
  template:
    metadata:
      labels:
        app: hackazon
    spec:
      containers:
      - name: hackazon
        image: harbor-01a.livefire.solutions/vulnerableapps/hackazon:latest
        ports:
        - containerPort: 80
